version: "3.6"

services:
  apidb:
    image: postgres
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_PASSWORD=password1
      - POSTGRES_USER=username1
      - POSTGRES_DB=databaseone1
    profiles:
      - dev

networks:
  project:
